---
# handlers/main.yml (ufw)
# Prefix : ufw

- name: "Print warning for ufw role (Check for deleted variables)"
  debug:
    msg: "{{ __ufw_check_vars.stdout_lines }}"
  failed_when: yes
  ignore_errors: yes
